### PR TITLE
Feature | District school markers

### PR DESCRIPTION
**Pull request by ThatcherK**
Ticket #151

### CODE REVIEW

**Comment by ThatcherK** [comment]
@pauline-n  This is ready for testing on the live pages, please note that I separated primary from secondary schools depending on the filter selected to reduce congestion. For Masindi its further divided in ownership, so for all the selected filters with number of schools, you get the corresponding schools shown in the map. I have not yet gotten rid of the schools outside the map boundaries, I will just exclude them with Javascript.

**Comment by pauline-n** [comment]
Hi @ThatcherK , this is great! am able to click and view the details of each school. The only thing I think that's not showing well is the color of the markers when you select secondary schools it looks a bit faint, is it possible to use different colors for secondary schools?

**Comment by ThatcherK** [comment]
Yeah it's possible, but I just want to use a single color that contrasts well against all backgrounds. Remember the shades keep changing depending on the data

**Comment by ThatcherK** [comment]
@Pauline, Check again, i have made the primary school color brighter, and changed the secondary school color. But perhaps I need to get a different shade, it doesnt look as bright as i thought. Any suggestions for a color to use for secondary?

**Comment by ThatcherK** [comment]
@pauline-n    Also another thing you should note is that the schools are placed in such a way that they don't overlap, so you are able to view more schools when you zoom out. But this setting can be removed if you wish so that all the schools are placed at once

**Comment by pauline-n** [comment]
Oh great I have seen the changes and yes we should think of a great color that can make them blend well with the colors of the maps. Will try to get some suggestions and share.

**Review by pauline-n — APPROVED** [review]

**Pull request merged**
